CREATE SEQUENCE EMP_SEQUENCE
 START WITH     11000
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

INSERT INTO "DEPARTMENT" (DEPARTID, CREATEDDATE, DEPARTNAME, MGR_ID) VALUES ('6000', TO_DATE('12-Jun-2010', 'DD-MON-RR'), 'HR', null);
/
INSERT INTO "DEPARTMENT" (DEPARTID, CREATEDDATE, DEPARTNAME, MGR_ID) VALUES ('6001', TO_DATE('12-Jun-2010', 'DD-MON-RR'), 'IT', null);
/
INSERT INTO "DEPARTMENT" (DEPARTID, CREATEDDATE, DEPARTNAME, MGR_ID) VALUES ('6002', TO_DATE('12-Jun-2010', 'DD-MON-RR'), 'admin', null);
/

INSERT INTO "EMPLOYEE" (ID, DATEOFBIRTH, DESIGNATION, FNAME, GENDER, JOINDATE, LNAME, LOGINNAME, MARITALSTATUS, MOBILENO, PASSWORD, SALARY, DEPTID, STATUS) 
VALUES 
('112', '11/11/1992', 'MANAGER', 'SHYAM', 'male', TO_DATE('13-JUN-15', 'DD-MON-RR'), 
  'reddy', 'admin', 'male', '9886386717', 'admin', '6000', '6002','Active');
/
INSERT INTO "EMPLOYEE" (ID, DATEOFBIRTH, DESIGNATION, FNAME, GENDER, JOINDATE, LNAME, LOGINNAME, MARITALSTATUS, MOBILENO, PASSWORD, SALARY, DEPTID) 
VALUES 
('113', '11/11/1993', 'MANAGER', 'RAM', 'male', TO_DATE('13-JUN-15', 'DD-MON-RR'), 
'KUMAR', 'user', 'male', '9886386717', 'user', '6000', '6002','Active');
/
commit;






INSERT INTO "EMPLOYEE" (ID, DATEOFBIRTH, DESIGNATION, FNAME, GENDER, JOINDATE, LNAME, LOGINNAME, MARITALSTATUS, MOBILENO, PASSWORD, SALARY, DEPTID, MANAGER_ID, EMPAGE) VALUES ('49', '1/11/1987', 'admin', 'ram', 'male', TO_DATE('10-JUN-2018', 'DD-MON-RR'), 'reddy', 'admin1', 'single', '9888766', 'admin1', '99999', '6002', '1', 65);
/                                                                           
INSERT INTO "EMPLOYEE" (ID, DATEOFBIRTH, DESIGNATION, FNAME, GENDER, JOINDATE, LNAME, LOGINNAME, PASSWORD, SALARY) VALUES ('2000', '12/07/1992', 'Senior software', 'Murali', 'male', TO_DATE('12-JUN-2010', 'DD-MON-RR'), 'reddy', 'murali', 'murali', '20000');
/
INSERT INTO "DEPARTMENT" (DEPARTID, CREATEDDATE, DEPARTNAME, MGR_ID) VALUES ('6000', TO_DATE('12-Jun-2010', 'DD-MON-RR'), 'HR', '2000');
/

INSERT INTO "EMPLOYEE" (ID, DATEOFBIRTH, DESIGNATION, FNAME, GENDER, JOINDATE, LNAME, LOGINNAME, PASSWORD, SALARY) VALUES ('2001', '12/07/1992', 'Senior software', 'Murali', 'male', TO_DATE('12-JUN-2010', 'DD-MON-RR'), 'reddy', 'vamsi', 'vamsi', '20000');
/
INSERT INTO "DEPARTMENT" (DEPARTID, CREATEDDATE, DEPARTNAME, MGR_ID) VALUES ('6001', TO_DATE('12-Jun-2010', 'DD-MON-RR'), 'IT', '2001');
/


INSERT INTO "EMPLOYEE" (ID, DATEOFBIRTH, DESIGNATION, FNAME, GENDER, JOINDATE, LNAME, LOGINNAME, PASSWORD, SALARY) VALUES ('2002', '12/07/1992', 'Senior software', 'admin', 'male', TO_DATE('12-JUN-2010', 'DD-MON-RR'), 'reddy', 'admin', 'admin', '20000');
/
INSERT INTO "DEPARTMENT" (DEPARTID, CREATEDDATE, DEPARTNAME, MGR_ID) VALUES ('6002', TO_DATE('12-Jun-2010', 'DD-MON-RR'), 'admin', '2002')
/
commit;

